#
# This pipeline needs the following tasks from Tekton Hub
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: main

  tasks:
    # --------------------------------------------------
    # Init / cleanup
    # --------------------------------------------------
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # --------------------------------------------------
    # Clone repo
    # --------------------------------------------------
    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - init
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    # --------------------------------------------------
    # Lint (flake8)
    # --------------------------------------------------
    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: python:3.9-slim
        - name: args
          value:
            - --count
            - --max-complexity=10
            - --max-line-length=127
            - --statistics

    # --------------------------------------------------
    # Tests (nose)
    # --------------------------------------------------
    - name: tests
      taskRef:
        name: nose
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: sqlite:///test.db
        - name: args
          value: "-v --with-spec --spec-color"